### ISSUE TITLE
Define email template for invitation to create a public state

### ISSUE THREAD

**Issue by schub** [momentarystates/momentarystates-backend#6]
When the admin creates a `Speculation`, an email address is specified. This email will receive an invitation to create a `PublicState`.  The text for this email needs to be specified.

Parameters to use in the email template:

- `invitedBy` - the username of the person who created the speculation
- `token` - the token which authorizes the invited person to create a public state
- `createUrl` - the landing page url which points to the UI where one can create the public state
  - Note: the url will already contain the token and the ID of the corresponding speculation
- `registerUrl` - the landing page url which points to the register UI

The email text should handle two different use cases. In the first one, the email is already known to the system and there is an existing user. In the second one the email is not known to the system and the person who receives the email first needs to register an account.

**Comment by frauhue** [comment]
done, see doc
